### ISSUE TITLE
Web-Socket

### ISSUE THREAD

**Issue by ToPraLLI** [goryn-clade/pathfinder#114]
Hello dear friends!

After installation, I am confused by this message in the setup section. This needs to be fixed somehow and tell me how if necessary.

Photo https://disk.yandex.ru/i/UburXPwe_vA-lQ

**Comment by MoNo7** [comment]
https://github.com/exodus4d/pathfinder_websocket   

I think one problem I had was it needed port 8030 even though it says 8020

**Comment by samoneilll** [comment]
Hi @ToPraLLI , did you get this solved?

**Comment by ToPraLLI** [comment]
Hello!
I was able to install the docker container and everything worked.

https://github.com/goryn-clade/pathfinder-containers
