### ISSUE TITLE
Error 500 - SQLSTATE[23000]

### ISSUE THREAD

**Issue by ParanoicEnt** [goryn-clade/pathfinder#117]
Just installed fresh  version of pf,during log in I am having this issue.
Any clue how to fix it?

![image](https://user-images.githubusercontent.com/29757408/168422406-e36d2910-fcdf-4624-b2f7-19289da8ae31.png)

**Comment by samoneilll** [comment]
Hi @ParanoicEnt, have you set up the databases on the setup page and imported the eve_universe sql dump?

**Comment by ParanoicEnt** [comment]
I set up database on /setup page,but had no idea about eve_universe.sql
Where i can find it?
Edit: Ah...I've found it...Gonna give it a try.

**Comment by samoneilll** [comment]
If you get stuck just pop into [slack](https://join.slack.com/t/pathfinder-eve-online/shared_invite/enQtMzMyOTkyMjczMTA3LWI2NGE1OTY5ODBmNDZlMDY3MDIzYjk5ZTljM2JjZjIwNDRkNzMyMTEwMDUzOGQwM2E3ZjE1NGEwNThlMzYzY2Y)
