### ISSUE TITLE
Missing combat/data sites

### ISSUE THREAD

**Issue by ghost** [goryn-clade/pathfinder#118]
Hi! I'm using the docker deployment for Pathfinder and it works like a charm! But I've realized that some entries are missing for combat and data sites, here's an example:

![pathfinder](https://user-images.githubusercontent.com/105872306/169331883-d3218f27-09eb-4c90-b5a2-7f4e753ea171.PNG)

This happens with the event ones too, maybe I did something wrong on the install? Any help or input would be great! Thank you so much for all the effort put onto this amazing tool!

**Comment by samoneilll** [comment]
Hey, 

Sorry about the slow reply. Event sites won't be added to PF. There's no published list of sites from CCP, so when they make new sites we have to manually add them to a list and publish a new version of pathfinder.

For that reason we won't add event sites. But if there are normal sites that are missing, feel free to add some data about them here and I'll try to add them in a future patch.

**Comment by fleischsalatinspace** [comment]
Related to https://github.com/goryn-clade/pathfinder/issues/135 and https://github.com/goryn-clade/pathfinder/issues/134

@weforgive i'll close this one as event sites are out of scope
