### ISSUE TITLE
[BUG] Thera Notification Spam

### ISSUE THREAD

**Issue by JustinGianelloni** [goryn-clade/pathfinder#122]
This is probably the edgiest of cases, but on the off chance there are two different signatures in Thera with a connection to the same system, Pathfinder will spam a notification every few seconds that the "Thera connections updated" until one of them is removed from eve-scout. It doesn't appear to break anything, but the notification spam is quite annoying.
![thera 1](https://user-images.githubusercontent.com/22803114/174463990-dac5a4d9-1550-476f-a523-1a550cb4aa89.jpg)
![thera 2](https://user-images.githubusercontent.com/22803114/174463991-2dd0899f-0ea8-4bf3-8d72-4a68037c788a.jpg)

**Comment by samoneilll** [comment]
Huh, interesting case, I'm not sure if it's worth trying to track down and solve given how rare it is that this could occur.
