### ISSUE TITLE
Corp Lookup for Structures Not Working

### ISSUE THREAD

**Issue by barndawgie** [goryn-clade/pathfinder#127]
I used Copy/Paste of D-Scan to add structures to a wormhole at https://pathfinder.lost-in-w.space/

When I try to set the Corp, it no longer auto-completes names but just says "No results found."

**Comment by lopho** [comment]
Looking for a fix as well.
This is what I have found out.
EDIT: linked to Issue in pathfinder_esi
repo https://github.com/goryn-clade/pathfinder_esi/issues/1

Seems like the ESI URI being used is wrong.
currently in this format:
```
https://esi.evetech.net/v2/search/?categories=corporation&search=CORP_SEACH_STRING&strict=false&datasouce=tranquility
```

This results in 404.
```
GuzzleHttp\Exception\ClientException, HTTP 404, Client error: `GET https://esi.evetech.net/v2/search/?categories=corporation&search=CORP_SEACH_STRING&strict=false&datasouce=tranquility` resulted in a `404 Not Found` response: {"error":"Not found"}
```

Checking the latest ESI API, the only "search" available is within the character group.
The following URI format should be used:
```
https://esi.evetech.net/v3/characters/AUTHED_CHARACTER_ID/search/?categories=corporation&datasource=tranquility&language=en&search=CORP_SEARCH_STRING&strict=false&token=ACCESS_TOKEN
```

This requires the additional scope:
```
esi-search.search_structures.v1
```
see https://esi.evetech.net/ui/?version=latest#/Search

Points of interest in codebase:
https://github.com/goryn-clade/pathfinder_esi/blob/master/app/Client/Ccp/Esi/Esi.php#L945

https://github.com/goryn-clade/pathfinder_esi/blob/master/app/Config/Ccp/Esi/Config.php#L160

**Comment by samoneilll** [comment]
Hey team, 

I am aware of this, I plan to fix it but I haven't had time over the past month or so. I'll do my best to get it in the next 2-4 weeks.

**Comment by turbofeedorglory** [comment]
https://github.com/goryn-clade/pathfinder-containers/pull/45
https://github.com/goryn-clade/pathfinder/pull/133
https://github.com/goryn-clade/pathfinder_esi/pull/2

**Comment by fleischsalatinspace** [comment]
Has been fixed with https://github.com/goryn-clade/pathfinder/releases/tag/v2.2.1
