### ISSUE TITLE
Unable to Add Other User's to CORP Map

### ISSUE THREAD

**Issue by zaxlofful** [goryn-clade/pathfinder#129]
I have created a CORP map in pathfinder, but it will not allow me to add other individual users; it only allows me to add other CORPs. I don't want to add an entire CORP access to the map, I just want to add an individual user.

Its also visa-versa for a private map. I am able to add other individual users, but I am not able to add CORPs to the share list.

Both of them have the same drawback, of not being able to add either an individual or a CORP to EITHER type of map.

**Comment by samoneilll** [comment]
This is how the author designed it, that corp maps should only be shared with corps, and alliance maps only be shared with alliances, etc. It is quite restrictive. 

One way around this to add an individual to a corp map is to add the whole corp to the map, and then only add the individual to the allow list in the .ini

The other thing you could look at is the "session sharing" feature which is documented in pathfinder.ini, and was designed to support using out of corp alts that can piggy back on the auth from the main.

**Comment by fleischsalatinspace** [comment]
@ZaxLofful if you need any help, please reopen the issue. Also if you join Pathfinder [Slack](https://join.slack.com/t/pathfinder-eve-online/shared_invite/enQtMzMyOTkyMjczMTA3LWI2NGE1OTY5ODBmNDZlMDY3MDIzYjk5ZTljM2JjZjIwNDRkNzMyMTEwMDUzOGQwM2E3ZjE1NGEwNThlMzYzY2Y) there are people that will help you :)
