### ISSUE TITLE
[Feature] - Drop Downs for Signatures Types in K-Space

### ISSUE THREAD

**Issue by barndawgie** [goryn-clade/pathfinder#134]
Currently, when pasting in/inputting scanned down signatures in J-Space, there is a drop down of possible site types. It would be great if this experience could be replicated in K-Space, e.g. in Angel NullSec there should be a drop down for Relic Sites with the choices Ruined Angel Temple Site, Ruined Angel Science Outpust, etc... rather than a free-text entry box.

**Comment by fleischsalatinspace** [comment]
IMO maybe this is out of scope, but lets keep in the feature backlog

**Comment by TyrHeimdalEVE** [comment]
Basically you'd have to map every single region based on their faction and then map an array for each faction including all the sites available there.

This would require too much work to be remotely worth it, sorry. Closing.
