### ISSUE TITLE
K162 Pochven Space

### ISSUE THREAD

**Issue by CalMatar** [goryn-clade/pathfinder#142]
I just found a wormhole to Pochven space, a K162 in my current wormhole and found that Pathfinder does not have the K162 side of the Pochven wormhole, F216, listed in the available dropdown menu. I am sure this is an oversight and should be an easy fix. 

Thank you for keeping this project alive.

**Comment by TyrHeimdalEVE** [comment]
[Are you sure about that?](https://i.imgur.com/0J5af4N.png)

As far as I can see, it was added in https://github.com/goryn-clade/pathfinder/commit/22855d49eb0640b404b0212290177dd9d9e533d1.
