### ISSUE TITLE
Map import not working

### ISSUE THREAD

**Issue by PinkKondur** [goryn-clade/pathfinder#150]
Importing maps is no longer working, even when trying to import right after you have done the export.
When you select the file and try to import you get the error: "Error undefined - Map data not valid (systems ||connections) missing."
![image](https://user-images.githubusercontent.com/70593503/204489346-4820360d-0b8c-42dd-8ba4-6d22877023c0.png)

**Comment by TyrHeimdalEVE** [comment]
I can't seem to replicate this issue, when exporting -> importing a map.

- Are you running v2.2.1?
- Was the map exported on v2.2.1?
- Did you select the file using "Choose File" or drop it?
- Which browser are you using?
- If you create a whole new map, add something, export it and import it - does it still fail?
