### ISSUE TITLE
Structures updated timer shouldn't be rounded to >1d

### ISSUE THREAD

**Issue by ElegosAkla** [goryn-clade/pathfinder#165]
About the updated column who display the time since the structure was last updated by a player.

How the things are now :
for data with less than 1 day old, it's fine and it show time with hours and minutes.
But for data older, it's only show ">1d."

I think it will be valuable to know the time more precisely.
Here is a easy fix to display the day count instead.

https://github.com/goryn-clade/pathfinder/compare/master...ElegosAkla:pathfinder:structurestimers-morethan1d

**Comment by TyrHeimdalEVE** [comment]
Hi! Please submit it as a PR and we'll merge it in the next version!
