### ISSUE TITLE
Sovereignty data incorrect 

### ISSUE THREAD

**Issue by rkben** [goryn-clade/pathfinder#167]
Pathfinder displays the incorrect system ownership for some systems.

![image](https://user-images.githubusercontent.com/22924645/220788079-5810f889-a5e7-4826-a2d5-6d9b8cb8d52b.png)

Correct information: https://evemaps.dotlan.net/system/TDP-T3

**Comment by TyrHeimdalEVE** [comment]
Cannot seem to replicate this issue. Something tells me that your Sov data might not be properly updated. This can be caused by for example the Cron not running or Redis being screwed up.

Ensure these are correct on the `/setup` page: https://i.imgur.com/kJFx4X4.png

**Comment by rkben** [comment]
Appears to have sorted itself since I opened the issue. Strange since that alliance hasnt held sov in that system since 2020.
