### ISSUE TITLE
Cannot update structure owning entity

### ISSUE THREAD

**Issue by ecortinas** [goryn-clade/pathfinder#168]
When I try to add an owning entity for a structure I get a 403 error.
![error](https://user-images.githubusercontent.com/88294949/221955867-9d1899e8-7335-4d76-bf00-9dd271a04f87.png)

**Comment by CalMatar** [comment]
I know this has to do with the updated ESI calls and the fact that CCP modified things. There is a fix on the Main Pathfinder GH Issues page with the fix but I do not know where it goes. I would like to make the update on my local version but have been unable to find it so far however I was working with exodus' code so maybe I can find it now with the cleaned up code of goryn-clade. If anyone knows where to find it let me know.

**Comment by TyrHeimdalEVE** [comment]
This issue is due to you missing the `esi-search.search_structures.v1` ESI scope in your `.env` file and/or your application on CCP's side (see: https://developers.eveonline.com/applications).

**Comment by CalMatar** [comment]
This is still not working even when the "updates" have been applied. Can you please contact me to maybe assist me with what may be incorrect or is that too much to ask? I have been attempting to fix this and it is extremely difficult to do when no one will answer any questions.
Thank you.
