### ISSUE TITLE
error code 403

### ISSUE THREAD

**Issue by StarCapsuleer-dotcom** [goryn-clade/pathfinder#176]
Pretty sure is error 403. so open up pathfinder then click game so pathfinder open in background every dang time go to it been logged out it's point of annoying tbh wish siggy was still here never issue. why does this do this???

**Comment by samoneilll** [comment]
Hi, do you run your own Patfhinder instance? There's some settings that define the length of a session and they can be set quite short. I believe the default is several hours though. If this isn't an instance that you run yourself, it might be best to get in touch with the person who manages to ask for assistance. 
If it is yours, maybe provide a few more details about what's happening. Any relevant logs from Patfinder, the average length of time before it kicks you out, anything in the browser console or network events, etc.
