### ISSUE TITLE
Specific Corporation is unable to login to pathfinder, throws 500 Error

### ISSUE THREAD

**Issue by LamboKenshin** [goryn-clade/pathfinder#179]
A cooperation in our Alliance is unable to log into Pathfinder. Not just one character in the cooperation, the entire cooperation. Yet they can log in just fine with any account outside the Corporation inside/outside the alliance, so long as its not in said Cooperation. Everyone has tried everything they can think to fix it, re login, reset token, clear cache, different computer, different internet. ect. Yet everyone keeps getting the same error message.

![opera_AJyVnZvave](https://user-images.githubusercontent.com/132532773/236099548-7583b33a-17a7-40f1-abac-25780281c9f9.png)

**Comment by lynkfox** [comment]
Whats the name of the Corporation? The error suggest that the json decoder is running into a character it does not recognize and therefor breaks - so if they have a funky character in the corp name that is probably part of the issue.

**Comment by TyrHeimdalEVE** [comment]
Closing as it's stale. If you're still having issues or updated information feel free to re-open.
