### ISSUE TITLE
EVE SSO Auth troubles

### ISSUE THREAD

**Issue by Raphyon** [goryn-clade/pathfinder#184]
Hi!

I recently tried installing my own docker image of pathfinder. My intensions were to host it locally "http://localhost/" as i want to use it as a test platform for myself. Upon creating the docker image the setup went pretty straight forward but i seem to be having issues with the auth platform.

The issue im getting is:
![image](https://github.com/goryn-clade/pathfinder/assets/72759908/caf212ff-3650-4ee7-ab82-93e6c737cb92)

This comes after clicking the log in button on the front page of pathfinder.
I have quadruple checked callbacks and such and cannot find any obvious issues with my knowledge about this.
If anyone has any experience with this i'd appreciate any help i can get!

**Comment by ElegosAkla** [comment]
You pathfinder instance need to be accessible from eve online server to work.
you can't host it locally to test it.

**Comment by TyrHeimdalEVE** [comment]
This isn't exactly true, as the SSO Callback URL needs to conform with whatever is registered in https://developers.eveonline.com/applications and this needs to correspond with what you set as the `DOMAIN` variable in your `.env` file, if using [pathfinder-containers](https://github.com/goryn-clade/pathfinder-containers).

I would advise to create a separate host for this, either by setting it in your `%WINDIR\system32\drivers\etc\hosts` or `/etc/hosts` on Linux (on the client side) or if you have a domain name, point it to whatever internal IP is assigned.

Usually pointing it to `127.0.0.1` (or `localhost`) is a bad idea, as this opens up the possibility to be used maliciously against you, and a lot of routers will filter them out to protect you (see [rebind protection](https://en.wikipedia.org/wiki/DNS_rebinding)). This generally goes for local addresses ([RFC 1918](https://en.wikipedia.org/wiki/Private_network)) too so if you go for the latter solution and it doesn't work - check your router configuration.
