### ISSUE TITLE
[BUG] Pasting citadels to structures module results in some results being deleted

### ISSUE THREAD

**Issue by samoneilll** [goryn-clade/pathfinder#20]
https://i.imgur.com/Um81v9c.gif

**Comment by samoneilll** [comment]
Confirmed that this bug does not exist in Pathfinder v2.0

**Comment by barndawgie** [comment]
I am able to reproduce this as well. If I add 3 structures via D-Scan, 2 are immediately deleted. If I add again, 1 is deleted - so I can only add 1 structure at a time via the D-Scan paste option.

**Comment by samoneilll** [comment]
Tracked down the issue. Structures were being saved correctly into the 'structure' table, however the associated 'corporation_structure' record that is used to build the systemData was being overwritten on each iteration when looping over structures in the pasted data, resulting in only the last structure on the list being properly persisted to the DB. 

I have solved by simply resetting the CorporationStructureModel instance when saving corporation structures ([f343753f](https://github.com/goryn-clade/pathfinder/commit/f343753f7d7b0964c0dc5cf16001be05b4657830)). I'm not sure if this is a good fix or a hacky one, but I know very little PHP, so unless anybody has a better solution I will include in the next release.
