### ISSUE TITLE
Switch to SSOv2

### ISSUE THREAD

**Issue by ppfeufer** [goryn-clade/pathfinder#38]
CCP is deprecating SSOv1 with the end of October/beginning November » https://developers.eveonline.com/blog/article/sso-endpoint-deprecations-2

**Comment by TyrHeimdalEVE** [comment]
We are aware, and are working on resolving the last few bits needed.

Will update here once the new version of pathfinder_esi is available.

**Comment by samoneilll** [comment]
should be solved in https://github.com/goryn-clade/pathfinder/pull/43/commits
