### ISSUE TITLE
ID doesn't have a default value

### ISSUE THREAD

**Issue by ppfeufer** [goryn-clade/pathfinder#39]
When trying to add structures to a system, I get the following error:

![image](https://user-images.githubusercontent.com/2989985/137193201-85b9361a-b405-4c8c-86df-f1a579f6c6e7.png)

![image](https://user-images.githubusercontent.com/2989985/137193258-0ee3cef8-8156-4abd-9a57-8e1a8578ca8f.png)

**Comment by samoneilll** [comment]
I've noticed a few buggy things with pasting structures, but I haven't encountered this one before. What type of structure was it?

**Comment by ppfeufer** [comment]
Citadels, Industry thingies, Upwell structures in general, but also tested scans that had Ihubs in it ...
