### ISSUE TITLE
Discord webhook

### ISSUE THREAD

**Issue by samoneilll** [goryn-clade/pathfinder#4]
https://github.com/exodus4d/pathfinder/issues/971#issuecomment-635204876

**Comment by TyrHeimdalEVE** [comment]
Maybe cherry-pick https://github.com/csatlos/pathfinder/commit/aa2827a96dba3b6c5ca69eebd42fab393d737b2f ?

**Comment by samoneilll** [comment]
Done, merged into dev2.1.1 branch.
