### ISSUE TITLE
[BUG] Invalid parameter number in api/Setup/buildIndex

### ISSUE THREAD

**Issue by oSkrobuk** [goryn-clade/pathfinder#45]
Hi.  I get this error when I click `Build` for `Systems neighbour index` on the setup page. How to fix it?

> 2021/10/24 21:08:18 [error] 27032#27032: *358 FastCGI sent in stderr: "PHP message: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens [/pathfinder/vendor/bcosca/fatfree-core/db/sql.php:230]PHP message: [vendor/bcosca/fatfree-core/db/sql.php:230] PDOStatement->execute()PHP message: [app/Lib/Db/Sql.php:116] DB\SQL->exec()PHP message: [app/Controller/Api/Setup.php:380] Exodus4D\Pathfinder\Lib\Db\Sql->exec()PHP message: [app/Controller/Api/Setup.php:206] Exodus4D\Pathfinder\Controller\Api\Setup->setupSystemJumpTable()PHP message: [index.php:27] Base->run()" while reading response header from upstream, client: 109.252.100.242, server: , request: "POST /api/Setup/buildIndex HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php-fpm.sock:", host: IP

**Comment by TyrHeimdalEVE** [comment]
Hi,

Which version of Pathfinder are you running? I've seen this issue too, but have not figured out the root cause yet.

**Comment by oSkrobuk** [comment]
> Hi,
> 
> Which version of Pathfinder are you running? I've seen this issue too, but have not figured out the root cause yet.

v2.1.3

**Comment by oSkrobuk** [comment]
On version 2.1.4 the same problem

**Comment by MorphedAU** [comment]
Have this issue as well with 2.1.4.

PHP 7.4.3
nginx version: nginx/1.18.0 (Ubuntu)

PHP message: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens [/var/www/pathfinder/vendor/bcosca/fatfree-core/db/sql.php:230]
PHP message: [vendor/bcosca/fatfree-core/db/sql.php:230] PDOStatement->execute()PHP message: [app/Lib/Db/Sql.php:116] DB\SQL->exec()
PHP message: [app/Controller/Api/Setup.php:380] Exodus4D\Pathfinder\Lib\Db\Sql->exec()
PHP message: [app/Controller/Api/Setup.php:206] Exodus4D\Pathfinder\Controller\Api\Setup->setupSystemJumpTable()
PHP message: [index.php:27] Base->run()

**Comment by oSkrobuk** [comment]
A parameter was added for a query, but this parameter is not called in the query. It is easy to solve. In this https://github.com/goryn-clade/pathfinder/blob/v2.1.4/app/Controller/Api/Setup.php#L352 replace 
```
                          `system`.`security` = :ns OR
                          `system`.`security` = :ls OR 
                          `system`.`security` = :hs
```
with
```
                          `system`.`security` = :ns OR
                          `system`.`security` = :ls OR 
                          `system`.`security` = :hs OR
                          `system`.`security` = :tr
```
But to do by analogy:
```
                      (
                          `system`.`security` = :ns OR
                          `system`.`security` = :ls OR 
                          `system`.`security` = :hs OR
                          `system`.`security` = :ts
                      )
                    HAVING 
                        `jumpNodes` IS NOT NULL
                    ";

        $args = [
            ':regionIdJove1' => 10000017,
            ':regionIdJove2' => 10000019,
            ':regionIdJove3' => 10000004,
            ':ns' => '0.0',
            ':ls' => 'L',
            ':hs' => 'H',
            ':ts' => 'T'
        ];
```

**Comment by MorphedAU** [comment]
Just made the above change in my install and looks like this fixes it. (It at least lets the job run!)

~~Though I think something is bugged with the Routes panel. When I have a K-Space connection it shows nothing, if I remove the K-Space connection I get the systems I've set show up as None.~~

**Comment by samoneilll** [comment]
@MorphedAU try opening the routes settings and saving it again. The route settings like minimum size, allow eol, allow crit, etc, are all stored in local storage. it's possible that the defaults aren't there so it doesn't find any routes. 

Just a hunch, but I think it's worth a try.

**Comment by TravisWhitehead** [comment]
@TyrHeimdalEVE Could you consider cutting a release with this fix? I hit this on the latest release. :)
