### ISSUE TITLE
[BUG] Unicode ship names

### ISSUE THREAD

**Issue by tiedyedguy** [goryn-clade/pathfinder#50]
In the local overlay if there is a ship with a unicode character it shows as the non-unicode way of displaying.

For instance, what comes over in the UserData json for my Astero is:

"u'\\xb2\\xb9\\u2564\\u041a\\u0440\\u0430\\u0441\\u0438\\u0432\\u044b\\u0439 \\u0431\\u0443\\u0431\\u043b\\u0438\\u043a'"

And that is what shows on the local overlay.  It doesn't help that my corp asks all ships to start with two unicode characters :)

The render for this and probably where to fix is at
https://github.com/goryn-clade/pathfinder/blob/master/js/app/map/local.js 
Line 187

I would mess myself but can't make new developer accounts on eve right now, so I can't work this one out myself :(

**Comment by tiedyedguy** [comment]
It might also be how the name is being saved into the database, like there is an extra encoding done.  Or maybe the DB is doing that extra encoding. I haven't figured that part out in the code yet :)

**Comment by samoneilll** [comment]
I think ship type/name are not stored in the db at all, they are pulled from ESI and cached in redis. I imagine that it's a front-end issue where it just needs url-decode on the shipname, but I will look into it when I can.

**Comment by tiedyedguy** [comment]
@samoneilll that was my thinking also a quick decodeURI might do it.

I love doing pull requests on software I use so as soon as eves developer application is working again I can test.

**Comment by samoneilll** [comment]
Reopening as this still seems to be an issue, see screenshot attached. Has anybody had any success with unicode shipnames? 

<img width="262" alt="Screenshot 2021-11-18 at 22 55 08" src="https://user-images.githubusercontent.com/30859143/142511926-6d84ad97-90b7-4d12-8754-c918996f8bac.png">

**Comment by samoneilll** [comment]
Looks like the previous fixed worked well in the active pilots modal from the top bar, but was not applied to the system node popover. I have fixed in [#d6fd9993291232a506a8ccadde1803df57d9bfe1](https://github.com/goryn-clade/pathfinder/commit/d6fd9993291232a506a8ccadde1803df57d9bfe1) and will merge in next release.
