### ISSUE TITLE
[BUG] Webhook for Discord Rally Point only works for j-space systems

### ISSUE THREAD

**Issue by Arm4g3ddon** [goryn-clade/pathfinder#59]
Webhook Discord Rallypoint not working.

After creating a rallypoint and selecting Discord poke nothing happens on the Discord channel.

Webhook for map updates works.

**Comment by jbuehlz** [comment]
Do you have any log data or can you elaborate further?

Docker installation or bare metal?

Discord rally points are working perfectly fine for my bare metal install.

**Comment by Arm4g3ddon** [comment]
I have checked the error log in the log folder but nothing to see there besides old errors. 

It is a bare metall installation with nginx.
What makes me wonder why the map update works but not the rally point.

The normal webserver logs show only one error: `1128999#0: *370072 no "charset_map" between the charsets "UTF-8" and "iso-8859-1" while reading response header from upstream`

This one is reported by nginx

I am using the version 2.1.4

**Comment by fleischsalatinspace** [comment]
On our instance on 2.1.4 this feature does work out of the box

**Comment by Arm4g3ddon** [comment]
What are you using? Docker?
I have also tried to set the rallypoint to a different channel on Discord. No Luck.

When I make a rallypoint with only Discord selected it should directly make an "ping" in discord right?
Even if nobody is currently in that system.

Best regards

**Comment by fleischsalatinspace** [comment]
We use https://github.com/goryn-clade/pathfinder-containers on several instances. Have you manually verified that your discord webhook is working? 
> When I make a rallypoint with only Discord selected it should directly make an "ping" in discord right?
Even if nobody is currently in that system.
Yes it should and does. I will verify on our instance regarding the "only discord selected"

**Comment by samoneilll** [comment]
I tested and found that the discord webhook only works when set on a j-space system. It does not work for k-space. I don't think this is intentional as there is no code to check the system-type.

**Comment by samoneilll** [comment]
Looks like it was the "true-sec" attribute in the webhook that was causing it to fail, floats are not valid and it causes the whole webhook to be invalid. 

Solved in [6161a95dd](https://github.com/goryn-clade/pathfinder/commit/6161a95dd01d7060a7b079302b6730e26aee59d7), will be included in the next release

**Comment by Arm4g3ddon** [comment]
Big thanks samoneilll great stuff!
