### ISSUE TITLE
SyntaxError: Unexpected token 0 in JSON at position 1

### ISSUE THREAD

**Issue by BrandXX** [goryn-clade/pathfinder#62]
For some reason I am getting a "SyntaxError: Unexpected token 0 in JSON at position 1" in the Zkillboard module. The GUI for the zKillboards has a red status indicator that states closed when I mouse over it. 

A little history, 
I upgraded my old exodus4d from this fork. The error occurred on my old installation so I though I would move  to a more recent Git repo but the problem persisted.

I'm not very strong in JS scripting, etc. Any help would be greatly appreciated.

**Comment by BrandXX** [comment]
Added some screenshots that I forgot to include.

![json_error](https://user-images.githubusercontent.com/39713461/139739270-72393791-f994-435e-8775-4b4d87820b59.png)

![zkillboard_status](https://user-images.githubusercontent.com/39713461/139739282-bb3f0cdf-bf3e-4d18-8ee8-12dc59516a5e.png)

**Comment by TyrHeimdalEVE** [comment]
Make sure your cache in both your browser and under /setup is flushed. This specific issue should afaik be fixed in v2.1.3.

**Comment by BrandXX** [comment]
For some reason or another that did not work. I did another clone and configured the INI's and I am good to go. Thanks for the help.

**Comment by TyrHeimdalEVE** [comment]
That's weird. Glad you got it sorted though!
