### ISSUE TITLE
ImageMagick

### ISSUE THREAD

**Issue by BrandXX** [goryn-clade/pathfinder#63]
I'm on GoDaddy Shared Linux hosting. I upgraded to 2.1.4 which ran for an hour before throwing this error.

Internal Server Error
Fatal error: PHP Startup: Unable to load dynamic library 'imagick.so' (tried: /opt/alt/php74/usr/lib64/php/modules/imagick.so (libMagickWand-7.Q16HDRI.so.7: cannot open shared object file: No such file or directory), /opt/alt/php74/usr/lib64/php/modules/imagick.so.so (/opt/alt/php74/usr/lib64/php/modules/imagick.so.so: cannot open shared object file: No such file or directory))

Any ideas? I am posted this on some forums as well. I cannot seem to get to the root of the cause.

**Comment by TyrHeimdalEVE** [comment]
You need to contact GoDaddy to get that fixed. It's trying to load a PHP module which isn't available.
