### ISSUE TITLE
[BUG] Wormhole data calculates incorrect size for some wormhole types

### ISSUE THREAD

**Issue by OpxSe** [goryn-clade/pathfinder#78]
As in Slack mentioned, here the bug 
![image](https://user-images.githubusercontent.com/43100235/142947914-19efdd30-8805-4f7f-827a-c8735492eb90.png)

>  Looks like hte problem is that ccp are still supplying those as 988m mass max, when the new size is 1350m or whatever, so there’s a function addWormholeSizeData() that calculates the size based on the max jumpable mass in the db and I guess it gets it wrong
> 
> if you make an issue on github we can work on it

**Comment by samoneilll** [comment]
This data comes from JS `Init.wormholes` object which appears to be created from a combination of eve_universe SDE and some helper functions to fill in extra data. 

mappage.js has a function `addWormholeSizeData()` which I assume is calculating the wrong size in some cases. It could be related to the recent increase in the jumpable mass of L and XL holes.

https://github.com/goryn-clade/pathfinder/blob/master/js/app/mappage.js#L80

As a side note, it appears that eve_universe.sql still has old jump masses, we should look at manually updating, or recreating the dump file by building from SDE.

**Comment by samoneilll** [comment]
solved in [e177ce0](https://github.com/goryn-clade/pathfinder/commit/e177ce0ea7734e98bace231c301ea178a928c25e)
