### ISSUE TITLE
[Feature] Abysall deadspace tracking should be disabled by default

### ISSUE THREAD

**Issue by samoneilll** [goryn-clade/pathfinder#83]
Tracking jumps to abysall deadspace PVE arenas has no practical value for most chain mapping usecases and just serves to create map clutter when a pilot forgets to turn off tracking before activating a filament. 

It's a useful feature to some users in some specific cases, but I believe it should be disabled by default when creating a new map.

**Comment by TyrHeimdalEVE** [comment]
We'd need abort if region ID is:
`12000001,12000002,12000003,12000004,12000005`

**Comment by TyrHeimdalEVE** [comment]
There is already if statements that uses the function `isAbyss()`:
https://github.com/goryn-clade/pathfinder/blob/58d9bb1ac2b11c6b6b0a44f613bf58a5a0ce6486/app/Model/Pathfinder/SystemModel.php#L711-L713

here:
https://github.com/goryn-clade/pathfinder/blob/58d9bb1ac2b11c6b6b0a44f613bf58a5a0ce6486/app/Controller/Api/Map.php#L857-L873

I do not see a good reason to track jumps to/from _any_ kind of Abyssal space, be it PVE or PVP arenas.
