### ISSUE TITLE
[bug] Pochven systems are assigned their pre-trig region/security

### ISSUE THREAD

**Issue by rremeaux** [goryn-clade/pathfinder#84]
Ala specifically, might be more?

**Comment by samoneilll** [comment]
Did you build your eve_universe from the eve_universe.sql.zip file? I have noticed that if you patch an existing database using the pochven/trailblazer patch then some systems can be wrong, but they should be correct in the full db dump.

In any case, if it's wrong, best thing to do would be to try dropping the eve_universe db and restore from here: 
https://github.com/goryn-clade/pathfinder/blob/master/export/sql/eve_universe.sql.zip


<img width="236" alt="image" src="https://user-images.githubusercontent.com/30859143/144950213-82910373-0256-4c10-b18b-3d949a0d1364.png">

**Comment by rremeaux** [comment]
Restoring the db as described fixed it, thanks. Sorry for the slow response. :)
