### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by mikesmith2107** [goryn-clade/pathfinder#86]
I have deployed a server for my Alliance, and currently limited to only my Alliance. I was thinking of opening it up to a private public server, where non alliance/members can use the server, for a small price. Members $1.99/month or alliance $20/100 members/month. With all excess funds from membership after hosting fees and taxes being Donated to the Project. Was seeking permission to do so, or Any Objections to this being Executed? Any Input is welcome

**Comment by fleischsalatinspace** [comment]
Hello,

there are several public Pathfinder instances free of charge available and also several hosting services which provide private Pathfinder hosting for ISK. Feel free to start your own service. Check the forum https://forums.eveonline.com/c/marketplace/services/61 or search with your favourite search engine for "eve online pathfinder hosting" for existing services. Also hop onto Pathfinder slack for community interaction.

I'll close this issue as its neither a BUG nor a FEATURE regarding Pathfinder itself . :)
