### ISSUE TITLE
Release 2.1.5

### ISSUE THREAD

**Issue by oSkrobuk** [goryn-clade/pathfinder#91]
When will 2.1.5 be released?

**Comment by leedickey** [comment]
A lack of a response concerns me for what is being touted as the community version.  Let's hope the holidays are the cause.

**Comment by fleischsalatinspace** [comment]
Holidays are indeed the reason. For direct communication hop onto slack :)

**Comment by oSkrobuk** [comment]
> Holidays are indeed the reason. For direct communication hop onto slack :)

Which workspace of the slack?
Link, pls :)

**Comment by fleischsalatinspace** [comment]
Pathfinder Slack from README in https://github.com/goryn-clade/pathfinder

https://join.slack.com/t/pathfinder-eve-online/shared_invite/enQtMzMyOTkyMjczMTA3LWI2NGE1OTY5ODBmNDZlMDY3MDIzYjk5ZTljM2JjZjIwNDRkNzMyMTEwMDUzOGQwM2E3ZjE1NGEwNThlMzYzY2Y
