### ISSUE TITLE
[BUG] call to a member function isActive() CharacterModel.php:1320

### ISSUE THREAD

**Issue by WouterGrin** [goryn-clade/pathfinder#98]
I get this error on only one of my characters. The rest of my characters work just fine. This is self hosted.
<img width="464" alt="37e0d9e0ab0858709e95b21fb97df391" src="https://user-images.githubusercontent.com/9049604/149623206-bad21d3b-3cf6-432e-b185-2bab5cf9ca6a.png">

**Comment by fleischsalatinspace** [comment]
Just for the record, what version are you running @WouterGrin  ?

**Comment by TyrHeimdalEVE** [comment]
Closing, this seems related to outdated `pathfinder-esi` and the OP never answered back.
